title: ItsHarveyTime
author: Christine Harvey
email: ceharvs@gmail.com
description: Christine's Portfolio
  
theme: minima

# social links
twitter_username: itsharveytime
github_username:  ceharvs

show_excerpts: true # set to false to remove excerpts on the homepage
